### PR TITLE
Developer help

### PR DESCRIPTION
**Pull request by indiegamehunt**

### CODE REVIEW

**Comment by hworld** [comment]
I thought I said to do them as separate PRs.

**Comment by indiegamehunt** [comment]
Oh I thought when we realized there would be 45 different branches and PRs, you were OK with one PR. I misunderstood. Should I redo it that way?

**Comment by hworld** [comment]
Yeah, split 'em up. I want to be able to merge them in separately.

**Comment by indiegamehunt** [comment]
Obsolete

**Pull request closed without merging**
